### ISSUE TITLE
Comando !run não funciona ou precisa de help

### ISSUE THREAD

**Issue by tiagoft** [JorasOliveira/NLP_discordBot#3]
Não consegui usar o !run corretamente:

![Uploading image.png…]()

**Comment by tiagoft** [comment]
![image](https://user-images.githubusercontent.com/3904558/224995535-feb88930-29d9-44e7-98b5-a950e4418cad.png)

**Comment by JorasOliveira** [comment]
agora !run sozinho traz uma mensagem de erro, pedindo para usar !help para saber a lista de comandos possiveis
